### ISSUE TITLE
As a user, I want to be able to use the `for_each` argument to provision multiple subnets using this module

### ISSUE THREAD

**Issue by jvallexm** [cloud-native-toolkit/terraform-ibm-vpc-subnets#35]
to provision multiple subnets across multiple zones requires duplication of the module. due to the `ibm_provider` block included the `for_each` argument is not supported in this module. removing this block would make it easier to provision multiple subnets in multiple zones using the same block

**Comment by seansund** [comment]
This issue has been resolved
