### ISSUE TITLE
Warning: Experimental feature "module_variable_optional_attrs" is active

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-ibm-vpc-subnets#60]
**Just FYI**

No roadblock so moving on

╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on .terraform/modules/ibm-vpc-subnets/version.tf line 10, in terraform:
│   10:   experiments = [module_variable_optional_attrs]

**Comment by smatthyssen** [comment]
@balasgit Can this issue be closed?

**Comment by seansund** [comment]
@balasgit This is by design. What is the problem?
